# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Farepay' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Farepay

	pod 'IQKeyboardManagerSwift'
	pod 'MaterialComponents/TextControls+FilledTextAreas'
	pod 'MaterialComponents/TextControls+FilledTextFields'
  pod 'StripeTerminal'
end
